SELECT USER_ID, PRODUCT_ID
FROM 
(SELECT
 USER_ID, PRODUCT_ID, COUNT(*) AS count 
FROM ONLINE_SALE
GROUP BY USER_ID, PRODUCT_ID
HAVING count(*) > 1) AS subquery
ORDER BY USER_ID ASC, PRODUCT_ID DESC;
