 SELECT ITEM_ID, ITEM_NAME, RARITY
 FROM ITEM_INFO
 WHERE ITEM_ID IN 
 (
 SELECT C.ITEM_ID
    FROM (SELECT * FROM ITEM_INFO WHERE RARITY = 'RARE') AS B
    INNER JOIN ITEM_TREE AS C
    ON B.ITEM_ID = C.PARENT_ITEM_ID
)
ORDER BY ITEM_ID DESC;