SELECT A.YEAR , B.SIZE - A.SIZE_OF_COLONY AS YEAR_DEV , A.ID
FROM
(SELECT ID, SIZE_OF_COLONY, YEAR(DIFFERENTIATION_DATE) AS YEAR FROM ECOLI_DATA) AS A
INNER JOIN 
(SELECT MAX(SIZE_OF_COLONY) AS SIZE, YEAR(DIFFERENTIATION_DATE) AS YEAR
FROM ECOLI_DATA
GROUP BY YEAR(DIFFERENTIATION_DATE)) AS B
ON A.YEAR =  B.YEAR
ORDER BY YEAR, YEAR_DEV;